### ISSUE TITLE
EAM-Double running Numbering Type for Clearance Permit Transaction

### ISSUE THREAD

**Issue by Senthilmurugan-B** [astpl1998/PPN-Power#13] opened 2021-02-20 12:59 UTC
@eafaisal,
Before start PFS we need discuss with karthik and Raju sir.

**Comment by eafaisal** [comment] 2021-03-16 09:32
@raju-kurup Sir,

PFS is completed.

[Double_Running_Numbering_Type_CLP.xlsx](https://github.com/astpl1998/PPN-Power/files/6147651/Double_Running_Numbering_Type_CLP.xlsx)

Regards,
Faisal

**Comment by raju-kurup** [comment] 2021-06-23 05:19
@karthikeyanamitysoft : please do the development as per PFS and discussed.

**Comment by Narendiranath** [comment] 2021-06-24 05:52
Hi Faisal,

As we discussed please mention below points 
1.In which screen you are going to create a work order against clearance permit 
2. where it will be stored clearance permit number .
3.what is the link of work order & clearance permit number.

Kindly update the PFS & Allocate to me. If any points i missed please mention that too also.

Regards,
Naren

**Comment by eafaisal** [comment] 2021-06-25 06:17
@Narendiranath 

The same data sheet is attached for clarifications.
Updated PFS is attached.

[Double_Running_Numbering_Type_CLP_V1.1.xlsx](https://github.com/astpl1998/PPN-Power/files/6713944/Double_Running_Numbering_Type_CLP_V1.1.xlsx)

Regards,
Faisal

**Comment by Narendiranath** [comment] 2021-06-28 17:59
Hi Faisal,

      Development completed. Kindly check and revert back. PFA Latest Deliverable for your ref.

[Deliverable V.1.zip](https://github.com/astpl1998/PPN-Power/files/6728332/Deliverable.V.1.zip)

Regards,
Naren

**Comment by eafaisal** [comment] 2021-06-29 04:17
@viki18790 

Kindly start the testing 1.

Regards,
Faisal

**Comment by eafaisal** [comment] 2021-06-29 12:40
@Narendiranath 

The clearance permit with double running series are created (Ex: CL/000046/21-22/00, CL/000046/21-22/01, CL/000046/21-22/02)
But while updating the clearance permit, this error is thrown. (pl see the screen shot)

![update_error](https://user-images.githubusercontent.com/65998153/123798627-ff39b280-d904-11eb-86cf-86499d21ccab.png)

Kindly check.

Regards,
Faisal

**Comment by eafaisal** [comment] 2021-07-02 04:22
@viki18790 

Kindly do the test again.

Regards,
Faisal

**Comment by Narendiranath** [comment] 2021-07-02 12:14
Hi Faisal,

         PFA Latest Deliverable for your ref.
[Deliverable V.6.zip](https://github.com/astpl1998/PPN-Power/files/6754488/Deliverable.V.6.zip)
Regards,
Naren

**Comment by viki18790** [comment] 2021-07-03 10:33
@eafaisal 

The Clearance Permit with double numbering series is  created as per logic given (Eg:  CL/000092/21-22/00, CL/000092/21-22/01, CL/000092/21-22/02),  but the activity specified in the Clearance Permit is not fetching. The Activity Multi-line has no data when viewing the Clearance Permit.

**Comment by eafaisal** [comment] 2021-07-03 12:16
RTrack is raised.
https://rtrackconnect.ramco.com/browse/PPNE-114

**Comment by eafaisal** [comment] 2021-07-05 08:55
For the Work Order WO/0055/21-22 three Clearance Permit were created.
They were created with double running series as per cutomer's requirement.

The Clearance Permits are as follows,
1. CL/000096/21-22/00
2. CL/000096/21-22/01
3. CL/000096/21-22/02

The screen shot is atatched.

![image](https://user-images.githubusercontent.com/65998153/124445015-cc783a00-dd9c-11eb-9eed-8b8d7bf71d8b.png)

Regards,
Faisal

**Comment by eafaisal** [comment] 2021-08-02 06:38
@raju-kurup  Sir,

There is an issue while creating Clearance Permit. After creating Clearance Permit, the activity in multi line is vanished.
Ramco is saying that because of the customization (double running series), this issue occurs.
Ramco comment is as follows, 
" Dear User,
Due to customization the issue was getting occurred. While creating clearance permit one clearance permit number is generating but in view screen showing different clearance permit number.
Please check the sequence without customization. If it is not working without customization, kindly revert" (R-Track PPNE-114).

Kindly move to development to proceed.

Regards,
Faisal

**Comment by raju-kurup** [comment] 2021-08-07 08:07
@karthikeyanamitysoft : As discussed, please do the needful for this issue.

**Comment by Narendiranath** [comment] 2021-08-11 11:14
Hi Faisal,

          Changes are done. Kindly check. PFA Latest Deliverables for your ref.

[Deliverable V.9.zip](https://github.com/astpl1998/PPN-Power/files/6967917/Deliverable.V.9.zip)

Regards,
Naren

**Comment by eafaisal** [comment] 2021-08-17 05:52
@raju-kurup Sir,

As per the customer's requirement, the double running series should start with '01' instead of '00'
(Ex. CL/000096/21-22/01)
The PFS is updated.
[Double_Running_Numbering_Type_CLP_V1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/6997376/Double_Running_Numbering_Type_CLP_V1.2.xlsx)

Kindly move to development to proceed.

Regards,
Faisal

**Comment by raju-kurup** [comment] 2021-08-18 05:43
@karthikeyanamitysoft : Running number should start from 01, now it is start with 00.  This to be done in test server

**Comment by karthikeyanamitysoft** [comment] 2021-08-18 06:00
number should start with 01 instead of 00

**Comment by Narendiranath** [comment] 2021-08-19 10:35
Hi Faisal,

          Above mentioned new changes are done. Kindly check. PFA Latest Delivrable for your ref.

[Deliverable V.10.zip](https://github.com/astpl1998/PPN-Power/files/7013691/Deliverable.V.10.zip)

Regards,
Naren

**Comment by eafaisal** [comment] 2021-08-28 07:37
Test Result: 
![Test Result Double Running Numbering Series](https://user-images.githubusercontent.com/65998153/131210431-9abe9953-56ff-426b-aa85-865e372d82a2.PNG)

**Comment by eafaisal** [comment] 2021-09-16 06:47
@raju-kurup Sir,

Customer agreed this report by email to deploy in live server.
![image](https://user-images.githubusercontent.com/65998153/133562784-7324e614-2fb1-4c43-8b4c-bef6cae6607b.png)
Mr.Solomon from PPN confirmed the same today (16.09.2021) by phone.
PFS: [Double_Running_Numbering_Type_CLP_V1.2.xlsx](https://github.com/astpl1998/PPN-Power/files/7175447/Double_Running_Numbering_Type_CLP_V1.2.xlsx)
Latest Deliverables: [Deliverable.V.10.zip](https://github.com/astpl1998/PPN-Power/files/7175470/Deliverable.V.10.zip)
Test Result 1: ![Testing1_Test_Result_Double_Running_Numbering_for_CP](https://user-images.githubusercontent.com/65998153/133563434-7b0b54ff-c8aa-4cbb-8c46-168dde455512.png)
Test Result 2: ![Testing2_Test_Result_Double_Running_Numbering_for_CP](https://user-images.githubusercontent.com/65998153/133563467-31f363fd-de2e-47c2-8a0b-ef85e22f6501.png)

Regards,
Faisal

**Comment by raju-kurup** [comment] 2021-09-16 08:03
@karthikeyanamitysoft ; please move this development from UAT to Live server and attach the deliverables in this ticket.

**Comment by Narendiranath** [comment] 2021-09-20 07:51
Hi Faisal,

             Live server deployment is completed. Kindly check & Revert back. PFA Latest deliverables for your ref.

[Deliverable V.11.zip](https://github.com/astpl1998/PPN-Power/files/7194260/Deliverable.V.11.zip)

Regards,
Naren

**Comment by eafaisal** [comment] 2021-10-05 02:36
@raju-kurup Sir,

Deployment in live server is completed.
Kindly close this ticket.

Regards,
Faisal

**Comment by raju-kurup** [comment] 2021-10-05 04:17
Accepted by customer and deployed in live server, so closing this ticket

**Closed by raju-kurup** 2021-10-05 04:17 UTC
Labels: 20.Deploy_DEV_Completed
